---

repo_url: https://raw.githubusercontent.com/ohidurbappy/fdroid/main/fdroid/repo
repo_name: Ohidur's F-Droid Repo
repo_description: >-
  This is an OFFICIAL Ohidur's android apps repository compatible with F-Droid.
  Applications in this repository are official binaries built by the original
  application developers.  

archive_older: 0
repo_icon: icon.png

repo_keyalias: localhost
keystore: keystore.p12
keystorepass: 1g5MuMlP89Fp1tL6QsshcvzX9ZHsvVlucclRaUaNJnw=
keypass: 1g5MuMlP89Fp1tL6QsshcvzX9ZHsvVlucclRaUaNJnw=

# The distinguished name used for all keys.
keydname: CN=localhost, OU=F-Droid

